// Code generated by hertz generator.

package social

import (
	"context"
	"video_website/pkg/errno"
	"video_website/pkg/jwt"
	"video_website/pkg/response"

	social "video_website/biz/model/social"
	socialService "video_website/biz/service/social"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

// RelationAction 关注/取关
// @router /relation/action [POST]
func RelationAction(ctx context.Context, c *app.RequestContext) {
	var req social.RelationActionReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	token := string(c.GetHeader("Access-Token"))
	if token == "" {
		response.SendResponse(c, errno.Unauthorized, nil)
		return
	}
	claims, err := jwt.ParseToken(token)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}

	if err := socialService.RelationAction(ctx, claims.UserID, req.ToUserID, req.ActionType); err != nil {
		response.SendResponse(c, err, nil)
		return
	}

	response.SendResponse(c, errno.Success, nil)
}

// FollowingList 关注列表
// @router /following/list [GET]
func FollowingList(ctx context.Context, c *app.RequestContext) {
	var req social.FollowingListReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	items, total, err := socialService.FollowingList(ctx, req.UserID, req.PageNum, req.PageSize)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}

	type followingData struct {
		Items []*social.SocialItemsResp `json:"items"`
		Total int32                     `json:"total"`
	}
	response.SendResponse(c, errno.Success, followingData{
		Items: items,
		Total: total,
	})
}

// FollowerList 粉丝列表
// @router /follower/list [GET]
func FollowerList(ctx context.Context, c *app.RequestContext) {
	var req social.FollowerListReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	items, total, err := socialService.FollowerList(ctx, req.UserID, req.PageNum, req.PageSize)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}

	type followerData struct {
		Items []*social.SocialItemsResp `json:"items"`
		Total int32                     `json:"total"`
	}
	response.SendResponse(c, errno.Success, followerData{
		Items: items,
		Total: total,
	})
}

// FriendsList 好友列表
// @router /friends/list [GET]
func FriendsList(ctx context.Context, c *app.RequestContext) {
	var req social.FriendsListReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	token := string(c.GetHeader("Access-Token"))
	if token == "" {
		response.SendResponse(c, errno.Unauthorized, nil)
		return
	}
	claims, err := jwt.ParseToken(token)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}

	items, total, err := socialService.FriendsList(ctx, claims.UserID, req.PageNum, req.PageSize)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}

	type friendsData struct {
		Items []*social.SocialItemsResp `json:"items"`
		Total int32                     `json:"total"`
	}
	response.SendResponse(c, errno.Success, friendsData{
		Items: items,
		Total: total,
	})
}
