// Code generated by hertz generator.

package social

import (
	"context"
	"video_website/biz/dal/mysql"
	"video_website/pkg/errno"
	"video_website/pkg/jwt"
	"video_website/pkg/response"

	social "video_website/biz/model/social"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

// RelationAction 关注
// @router /relation/action [POST]
func RelationAction(ctx context.Context, c *app.RequestContext) {
	var req social.RelationActionReq
	if err := c.BindAndValidate(&req); err != nil {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	token := string(c.GetHeader("Access-Token"))
	if token == "" {
		response.SendResponse(c, errno.Unauthorized, nil)
		return
	}
	claims, err := jwt.ParseToken(token)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}
	followerID := claims.UserID

	if err := mysql.FollowAction(ctx, followerID, req.ToUserID, req.ActionType); err != nil {
		hlog.CtxErrorf(ctx, "关注操作失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}

	response.SendResponse(c, errno.Success, nil)
}

// FollowingList 关注列表
// @router /following/list [GET]
func FollowingList(ctx context.Context, c *app.RequestContext) {
	var req social.FollowingListReq
	if err := c.BindAndValidate(&req); err != nil {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	followingIDs, total, err := mysql.GetFollowing(ctx, req.UserID, req.PageNum, req.PageSize)
	if err != nil {
		hlog.CtxErrorf(ctx, "查询关注列表失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}

	items := make([]*social.SocialItemsResp, 0, len(followingIDs))
	for _, id := range followingIDs {
		u, err := mysql.GetUserByID(ctx, id)
		if err != nil || u == nil {
			continue
		}
		items = append(items, &social.SocialItemsResp{
			ID:        u.ID,
			Username:  u.Username,
			AvatarURL: u.AvatarURL,
		})
	}

	type followingData struct {
		Items []*social.SocialItemsResp `json:"items"`
		Total int32                     `json:"total"`
	}

	response.SendResponse(c, errno.Success, followingData{
		Items: items,
		Total: int32(total),
	})
}

// FollowerList 粉丝列表
// @router /follower/list [GET]
func FollowerList(ctx context.Context, c *app.RequestContext) {
	var req social.FollowerListReq
	if err := c.BindAndValidate(&req); err != nil {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	followerIDs, total, err := mysql.GetFollowers(ctx, req.UserID, req.PageNum, req.PageSize)
	if err != nil {
		hlog.CtxErrorf(ctx, "查询粉丝列表失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}

	items := make([]*social.SocialItemsResp, 0, len(followerIDs))
	for _, id := range followerIDs {
		u, err := mysql.GetUserByID(ctx, id)
		if err != nil || u == nil {
			continue
		}
		items = append(items, &social.SocialItemsResp{
			ID:        u.ID,
			Username:  u.Username,
			AvatarURL: u.AvatarURL,
		})
	}

	type followerData struct {
		Items []*social.SocialItemsResp `json:"items"`
		Total int32                     `json:"total"`
	}

	response.SendResponse(c, errno.Success, followerData{
		Items: items,
		Total: int32(total),
	})
}

// FriendsList 好友列表
// @router /friends/list [GET]
func FriendsList(ctx context.Context, c *app.RequestContext) {
	var req social.FriendsListReq
	if err := c.BindAndValidate(&req); err != nil {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	token := string(c.GetHeader("Access-Token"))
	if token == "" {
		response.SendResponse(c, errno.Unauthorized, nil)
		return
	}
	claims, err := jwt.ParseToken(token)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}
	userID := claims.UserID

	friendIDs, total, err := mysql.GetFriends(ctx, userID, req.PageNum, req.PageSize)
	if err != nil {
		hlog.CtxErrorf(ctx, "查询好友列表失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}

	items := make([]*social.SocialItemsResp, 0, len(friendIDs))
	for _, id := range friendIDs {
		u, err := mysql.GetUserByID(ctx, id)
		if err != nil || u == nil {
			continue
		}
		items = append(items, &social.SocialItemsResp{
			ID:        u.ID,
			Username:  u.Username,
			AvatarURL: u.AvatarURL,
		})
	}

	type friendsData struct {
		Items []*social.SocialItemsResp `json:"items"`
		Total int32                     `json:"total"`
	}

	response.SendResponse(c, errno.Success, friendsData{
		Items: items,
		Total: int32(total),
	})
}
