// Code generated by hertz generator.

package interaction

import (
	"context"
	"time"
	"video_website/biz/dal/mysql"
	"video_website/biz/dal/mysql/entity"
	"video_website/biz/dal/redis"
	"video_website/pkg/errno"
	"video_website/pkg/jwt"
	"video_website/pkg/response"
	"video_website/pkg/utils"

	interaction "video_website/biz/model/interaction"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

// LikeAction 点赞
// @router /like/action [POST]
func LikeAction(ctx context.Context, c *app.RequestContext) {
	var req interaction.LikeActionReq
	if err := c.BindAndValidate(&req); err != nil {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	token := string(c.GetHeader("Access-Token"))
	if token == "" {
		response.SendResponse(c, errno.Unauthorized, nil)
		return
	}
	claims, err := jwt.ParseToken(token)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}
	userID := claims.UserID

	actionType := int32(0)
	if req.ActionType == "1" {
		actionType = int32(1)
	} else if req.ActionType == "2" {
		actionType = int32(2)
	} else {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	if err := mysql.LikeAction(ctx, userID, req.VideoID, actionType); err != nil {
		hlog.CtxErrorf(ctx, "点赞操作失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}

	response.SendResponse(c, errno.Success, nil)
	redis.RDB.Del(ctx, "popular:videos")
}

// LikeList 点赞列表
// @router /like/list [POST]
func LikeList(ctx context.Context, c *app.RequestContext) {
	var req interaction.LikeListReq
	if err := c.BindAndValidate(&req); err != nil {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	videoIDs, _, err := mysql.GetUserLikedVideoIDs(ctx, req.UserID, req.PageNum, req.PageSize)
	if err != nil {
		hlog.CtxErrorf(ctx, "查询点赞列表失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}

	items := make([]*interaction.InteractionItemsResp, 0, len(videoIDs))
	for _, videoID := range videoIDs {
		items = append(items, &interaction.InteractionItemsResp{
			ID: videoID,
		})
	}

	resp := &interaction.LikeListResp{
		Items: items,
	}
	response.SendResponse(c, errno.Success, resp)
}

// CommentPublish 发表评论
// @router /comment/publish [POST]
func CommentPublish(ctx context.Context, c *app.RequestContext) {
	var req interaction.CommentPublishReq
	if err := c.BindAndValidate(&req); err != nil {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	token := string(c.GetHeader("Access-Token"))
	if token == "" {
		response.SendResponse(c, errno.Unauthorized, nil)
		return
	}
	claims, err := jwt.ParseToken(token)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}
	userID := claims.UserID

	comment := &entity.Comment{
		ID:        utils.GenerateID(),
		UserID:    userID,
		VideoID:   req.VideoID,
		Content:   req.Content,
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}
	if err := mysql.CreateComment(ctx, userID, req.VideoID, comment); err != nil {
		hlog.CtxErrorf(ctx, "发表评论失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}

	response.SendResponse(c, errno.Success, nil)
}

// CommentList 评论列表
// @router /comment/list [POST]
func CommentList(ctx context.Context, c *app.RequestContext) {
	var req interaction.CommentListReq
	if err := c.BindAndValidate(&req); err != nil {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	comments, _, err := mysql.GetCommentsByVideoID(ctx, req.VideoID, req.PageNum, req.PageSize)
	if err != nil {
		hlog.CtxErrorf(ctx, "查询评论列表失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}

	items := make([]*interaction.InteractionItemsResp, 0, len(comments))
	for _, c := range comments {
		items = append(items, &interaction.InteractionItemsResp{
			ID:     c.ID,
			UserID: c.UserID,
		})
	}

	resp := &interaction.CommentListResp{
		Items: items,
	}

	response.SendResponse(c, errno.Success, resp)
}

// CommentDelete 删除评论
// @router /comment/delete [POST]
func CommentDelete(ctx context.Context, c *app.RequestContext) {
	var req interaction.CommentDeleteReq
	if err := c.BindAndValidate(&req); err != nil {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	token := string(c.GetHeader("Access-Token"))
	if token == "" {
		response.SendResponse(c, errno.Unauthorized, nil)
		return
	}
	claims, err := jwt.ParseToken(token)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}
	userID := claims.UserID

	if err := mysql.DeleteComment(ctx, req.CommentID, userID); err != nil {
		hlog.CtxErrorf(ctx, "删除评论失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}

	response.SendResponse(c, errno.Success, nil)
}
