// Code generated by hertz generator.

package interaction

import (
	"context"
	"strings"
	"time"
	"video_website/biz/dal/mysql"
	"video_website/biz/dal/mysql/entity"
	"video_website/biz/dal/redis"
	"video_website/pkg/errno"
	"video_website/pkg/jwt"
	"video_website/pkg/response"
	"video_website/pkg/utils"

	interaction "video_website/biz/model/interaction"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

// LikeAction 点赞
// @router /like/action [POST]
func LikeAction(ctx context.Context, c *app.RequestContext) {
	var req interaction.LikeActionReq
	if err := c.BindAndValidate(&req); err != nil {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	token := string(c.GetHeader("Access-Token"))
	if token == "" {
		response.SendResponse(c, errno.Unauthorized, nil)
		return
	}
	claims, err := jwt.ParseToken(token)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}
	userID := claims.UserID

	actionType := int32(0)
	if req.ActionType == "1" {
		actionType = 1
	} else if req.ActionType == "2" {
		actionType = 2
	} else {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	cleanVideoID := strings.Trim(req.VideoID, "\"")

	if err := mysql.LikeAction(ctx, userID, cleanVideoID, actionType); err != nil {
		hlog.CtxErrorf(ctx, "点赞操作失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}

	// 删除热门视频缓存
	redis.RDB.Del(ctx, "popular:videos")

	response.SendResponse(c, errno.Success, nil)
}

// LikeList 点赞列表
// @router /like/list [GET]
func LikeList(ctx context.Context, c *app.RequestContext) {
	var req interaction.LikeListReq
	if err := c.BindAndValidate(&req); err != nil {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	videoIDs, total, err := mysql.GetUserLikedVideoIDs(ctx, req.UserID, req.PageNum, req.PageSize)
	if err != nil {
		hlog.CtxErrorf(ctx, "查询点赞列表失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}

	hlog.CtxInfof(ctx, "获取到点赞视频ID列表: %v, 总数: %d", videoIDs, total)

	if len(videoIDs) == 0 {
		response.SendResponse(c, errno.Success, []*interaction.InteractionItemsResp{})
		return
	}

	cleanedIDs := make([]string, 0, len(videoIDs))
	for _, id := range videoIDs {
		cleanedIDs = append(cleanedIDs, strings.Trim(id, "\""))
	}
	hlog.CtxInfof(ctx, "清洗后的视频ID列表: %v", cleanedIDs)

	videos, err := mysql.GetVideosByIDs(ctx, cleanedIDs)
	if err != nil {
		hlog.CtxErrorf(ctx, "查询视频信息失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}
	hlog.CtxInfof(ctx, "查询到视频数量: %d", len(videos))

	videoMap := make(map[string]*entity.Video, len(videos))
	for _, v := range videos {
		videoMap[v.ID] = v
	}

	items := make([]*interaction.InteractionItemsResp, 0, len(videoIDs))
	for _, originalID := range videoIDs {
		cleanID := strings.Trim(originalID, "\"")
		v, ok := videoMap[cleanID]
		if !ok {
			items = append(items, &interaction.InteractionItemsResp{
				ID: cleanID,
			})
			hlog.CtxInfof(ctx, "视频ID %s 不存在，仅返回ID", cleanID)
			continue
		}
		items = append(items, &interaction.InteractionItemsResp{
			ID:           v.ID,
			UserID:       v.UserID,
			VideoURL:     v.VideoURL,
			CoverURL:     v.CoverURL,
			Title:        v.Title,
			Description:  v.Description,
			VisitCount:   int32(v.VisitCount),
			LikeCount:    int32(v.LikeCount),
			CommentCount: int32(v.CommentCount),
			CreatedAt:    v.CreatedAt.Format("2006-01-02 15:04:05"),
			UpdatedAt:    v.UpdatedAt.Format("2006-01-02 15:04:05"),
			DeletedAt:    "",
		})
	}

	response.SendResponse(c, errno.Success, items)
}

// CommentPublish 发表评论
// @router /comment/publish [POST]
func CommentPublish(ctx context.Context, c *app.RequestContext) {
	var req interaction.CommentPublishReq
	if err := c.BindAndValidate(&req); err != nil {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	token := string(c.GetHeader("Access-Token"))
	if token == "" {
		response.SendResponse(c, errno.Unauthorized, nil)
		return
	}
	claims, err := jwt.ParseToken(token)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}
	userID := claims.UserID

	comment := &entity.Comment{
		ID:        utils.GenerateID(),
		UserID:    userID,
		VideoID:   req.VideoID,
		Content:   req.Content,
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}
	if err := mysql.CreateComment(ctx, userID, req.VideoID, comment); err != nil {
		hlog.CtxErrorf(ctx, "发表评论失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}

	response.SendResponse(c, errno.Success, nil)
}

// CommentList 评论列表
// @router /comment/list [GET]
func CommentList(ctx context.Context, c *app.RequestContext) {
	var req interaction.CommentListReq
	if err := c.BindAndValidate(&req); err != nil {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	comments, _, err := mysql.GetCommentsByVideoID(ctx, req.VideoID, req.PageNum, req.PageSize)
	if err != nil {
		hlog.CtxErrorf(ctx, "查询评论列表失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}

	items := make([]*interaction.CommentItemResp, 0, len(comments))
	for _, comment := range comments {
		items = append(items, &interaction.CommentItemResp{
			ID:        comment.ID,
			UserID:    comment.UserID,
			Content:   comment.Content,
			CreatedAt: comment.CreatedAt.Format("2006-01-02 15:04:05"),
			UpdatedAt: comment.UpdatedAt.Format("2006-01-02 15:04:05"),
			DeletedAt: "",
		})
	}

	response.SendResponse(c, errno.Success, items)
}

// CommentDelete 删除评论
// @router /comment/delete [DELETE]
func CommentDelete(ctx context.Context, c *app.RequestContext) {
	var req interaction.CommentDeleteReq
	if err := c.BindAndValidate(&req); err != nil {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	token := string(c.GetHeader("Access-Token"))
	if token == "" {
		response.SendResponse(c, errno.Unauthorized, nil)
		return
	}
	claims, err := jwt.ParseToken(token)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}
	userID := claims.UserID

	if err := mysql.DeleteComment(ctx, req.CommentID, userID); err != nil {
		hlog.CtxErrorf(ctx, "删除评论失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}

	response.SendResponse(c, errno.Success, nil)
}
