// Code generated by hertz generator.

package interaction

import (
	"context"
	"video_website/biz/middleware/jwt"
	"video_website/pkg/errno"
	"video_website/pkg/response"

	interaction "video_website/biz/model/interaction"
	interactionService "video_website/biz/service/interaction"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

// LikeAction 点赞操作
// @router /interaction/like/action [POST]
func LikeAction(ctx context.Context, c *app.RequestContext) {
	var req interaction.LikeActionReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	userID := jwt.GetUserID(ctx, c)

	if err := interactionService.LikeAction(ctx, userID, req.VideoID, req.CommentID, req.ActionType); err != nil {
		response.SendResponse(c, err, nil)
		return
	}

	response.SendResponse(c, errno.Success, nil)
}

// LikeList 点赞列表
// @router /interaction/like/list [GET]
func LikeList(ctx context.Context, c *app.RequestContext) {
	var req interaction.LikeListReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	items, err := interactionService.LikeList(ctx, req.UserID, req.PageNum, req.PageSize)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}

	response.SendResponse(c, errno.Success, items)
}

// CommentPublish 评论投稿
// @router /interaction/comment/publish [POST]
func CommentPublish(ctx context.Context, c *app.RequestContext) {
	var req interaction.CommentPublishReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	userID := jwt.GetUserID(ctx, c)
	if err := interactionService.CommentPublish(ctx, userID, req.VideoID, req.CommentID, req.Content); err != nil {
		response.SendResponse(c, err, nil)
		return
	}

	response.SendResponse(c, errno.Success, nil)
}

// CommentList 评论列表
// @router /interaction/comment/list [GET]
func CommentList(ctx context.Context, c *app.RequestContext) {
	var req interaction.CommentListReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	items, err := interactionService.CommentList(ctx, req.VideoID, req.PageNum, req.PageSize)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}

	response.SendResponse(c, errno.Success, items)
}

// CommentDelete 评论删除
// @router /interaction/comment/delete [POST]
func CommentDelete(ctx context.Context, c *app.RequestContext) {
	var req interaction.CommentDeleteReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	userID := jwt.GetUserID(ctx, c)
	if err := interactionService.CommentDelete(ctx, req.CommentID, userID); err != nil {
		response.SendResponse(c, err, nil)
		return
	}

	response.SendResponse(c, errno.Success, nil)
}
