// Code generated by hertz generator.

package user

import (
	"video_website/biz/middleware/jwt"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	return nil
}

func _authMw() []app.HandlerFunc {
	return nil
}

func _mfaMw() []app.HandlerFunc {
	return nil
}

func _bindmfaMw() []app.HandlerFunc {
	return []app.HandlerFunc{jwt.AuthMiddleware()}
}

func _getmfaMw() []app.HandlerFunc {
	return []app.HandlerFunc{jwt.AuthMiddleware()}
}

func _userMw() []app.HandlerFunc {
	return nil
}

func _infoMw() []app.HandlerFunc {
	return []app.HandlerFunc{jwt.AuthMiddleware()}
}

func _loginMw() []app.HandlerFunc {
	return nil
}

func _refreshMw() []app.HandlerFunc {
	return nil
}

func _registerMw() []app.HandlerFunc {
	return nil
}

func _avatarMw() []app.HandlerFunc {
	return nil
}

func _uploadavatarMw() []app.HandlerFunc {
	return []app.HandlerFunc{jwt.AuthMiddleware()}
}
