version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - gocritic
    - govet
    - gosec
    - gci
    - ineffassign
    - misspell
    - staticcheck
    - bodyclose
  disable:
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - dupl
    - funlen
    - lll
    - prealloc
    - revive
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - unused


issues:
  max-issues-per-linter: 0
  max-same-issues: 0
