version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: video_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: video_website
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: video_redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: video_website
    ports:
      - "8888:8888"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network
    environment:
        MYSQL_DSN: "root:123456@tcp(mysql:3306)/video_website?charset=utf8mb4&parseTime=True&loc=Local"
        REDIS_ADDR: "redis:6379"
    volumes:
      - ./config/config.yaml:/root/config/config.yaml
      - ./static:/root/static

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge