// Code generated by hertz generator.

package main

import (
	"net/http"
	"video_website/biz/dal/mysql"
	"video_website/biz/dal/redis"
	chatHandler "video_website/biz/handler/chat"
	"video_website/biz/router"
	chatService "video_website/biz/service/chat"
	"video_website/config"
	"video_website/pkg/jwt"
	"video_website/pkg/utils"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

func main() {
	config.InitConfig()

	jwt.Init(config.Conf.JWT.Secret)

	if err := utils.InitSnowflake("2023-01-01", 1); err != nil {
		hlog.Fatal("初始化雪花ID失败", err)
	}

	if err := mysql.Init(config.Conf.MySQL.DSN); err != nil {
		hlog.Fatal("数据库初始化失败", err)
	}

	if err := redis.Init(); err != nil {
		hlog.Fatal("Redis初始化失败:", err)
	}

	chatService.InitHub()

	h := server.Default(server.WithHostPorts(config.Conf.Server.Address))

	h.Static("/static", "./")

	router.GeneratedRegister(h)

	go func() {
		http.HandleFunc("/ws", chatHandler.HTTPWebSocketHandler)
		hlog.Infof("WebSocket 服务已启动: ws://localhost:6666/ws")
		if err := http.ListenAndServe(":6666", nil); err != nil {
			hlog.Fatalf("WebSocket服务启动失败: %v", err)
		}
	}()

	h.Spin()
}
