// Code generated by hertz generator.

package main

import (
	"video_website/biz/dal/mysql"
	"video_website/biz/dal/redis"
	"video_website/config"
	"video_website/pkg/jwt"
	"video_website/pkg/utils"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

func main() {
	config.InitConfig()

	jwt.Init(config.Conf.JWT.Secret)

	if err := utils.InitSnowflake("2023-01-01", 1); err != nil {
		hlog.Fatal("初始化雪花ID失败", err)
	}

	if err := mysql.Init(config.Conf.MySQL.DSN); err != nil {
		hlog.Fatal("数据库初始化失败", err)
	}

	if err := redis.Init(); err != nil {
		hlog.Fatal("Redis初始化失败:", err)
	}

	h := server.Default(server.WithHostPorts(config.Conf.Server.Address))

	register(h)
	h.Spin()
}
