// Code generated by hertz generator.

package video

import (
	"video_website/biz/middleware/jwt"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _popularMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishMw() []app.HandlerFunc {
	return []app.HandlerFunc{jwt.AuthMiddleware()}
}

func _searchMw() []app.HandlerFunc {
	// your code...
	return nil
}