// Code generated by hertz generator.

package social

import (
	"video_website/biz/middleware/jwt"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	return nil
}

func _followerMw() []app.HandlerFunc {
	return nil
}

func _followerlistMw() []app.HandlerFunc {
	return []app.HandlerFunc{jwt.AuthMiddleware()}
}

func _followingMw() []app.HandlerFunc {
	return nil
}

func _followinglistMw() []app.HandlerFunc {
	return []app.HandlerFunc{jwt.AuthMiddleware()}
}

func _friendsMw() []app.HandlerFunc {
	return nil
}

func _friendslistMw() []app.HandlerFunc {
	return []app.HandlerFunc{jwt.AuthMiddleware()}
}

func _relationMw() []app.HandlerFunc {
	return nil
}

func _relationactionMw() []app.HandlerFunc {
	return []app.HandlerFunc{jwt.AuthMiddleware()}
}
