// Code generated by hertz generator.

package interaction

import (
	"video_website/biz/middleware/jwt"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	return nil
}

func _commentMw() []app.HandlerFunc {
	return nil
}

func _commentdeleteMw() []app.HandlerFunc {
	return []app.HandlerFunc{jwt.AuthMiddleware()}
}

func _commentlistMw() []app.HandlerFunc {
	return []app.HandlerFunc{jwt.AuthMiddleware()}
}

func _commentpublishMw() []app.HandlerFunc {
	return []app.HandlerFunc{jwt.AuthMiddleware()}
}

func _likeMw() []app.HandlerFunc {
	return nil
}

func _likeactionMw() []app.HandlerFunc {
	return []app.HandlerFunc{jwt.AuthMiddleware()}
}

func _likelistMw() []app.HandlerFunc {
	return []app.HandlerFunc{jwt.AuthMiddleware()}
}
