// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package interaction

import (
	"context"
	"fmt"
	"video_website/biz/model/base"
)

type InteractionItemsResp struct {
	ID           string `thrift:"id,1" form:"id" json:"id" query:"id"`
	UserID       string `thrift:"user_id,2" form:"user_id" json:"user_id" query:"user_id"`
	VideoURL     string `thrift:"video_url,3" form:"video_url" json:"video_url" query:"video_url"`
	CoverURL     string `thrift:"cover_url,4" form:"cover_url" json:"cover_url" query:"cover_url"`
	Title        string `thrift:"title,5" form:"title" json:"title" query:"title"`
	Description  string `thrift:"description,6" form:"description" json:"description" query:"description"`
	VisitCount   int32  `thrift:"visit_count,7" form:"visit_count" json:"visit_count" query:"visit_count"`
	LikeCount    int32  `thrift:"like_count,8" form:"like_count" json:"like_count" query:"like_count"`
	CommentCount int32  `thrift:"comment_count,9" form:"comment_count" json:"comment_count" query:"comment_count"`
	CreatedAt    string `thrift:"created_at,10" form:"created_at" json:"created_at" query:"created_at"`
	UpdatedAt    string `thrift:"updated_at,11" form:"updated_at" json:"updated_at" query:"updated_at"`
	DeletedAt    string `thrift:"deleted_at,12" form:"deleted_at" json:"deleted_at" query:"deleted_at"`
}

func NewInteractionItemsResp() *InteractionItemsResp {
	return &InteractionItemsResp{}
}

func (p *InteractionItemsResp) InitDefault() {
}

func (p *InteractionItemsResp) GetID() (v string) {
	return p.ID
}

func (p *InteractionItemsResp) GetUserID() (v string) {
	return p.UserID
}

func (p *InteractionItemsResp) GetVideoURL() (v string) {
	return p.VideoURL
}

func (p *InteractionItemsResp) GetCoverURL() (v string) {
	return p.CoverURL
}

func (p *InteractionItemsResp) GetTitle() (v string) {
	return p.Title
}

func (p *InteractionItemsResp) GetDescription() (v string) {
	return p.Description
}

func (p *InteractionItemsResp) GetVisitCount() (v int32) {
	return p.VisitCount
}

func (p *InteractionItemsResp) GetLikeCount() (v int32) {
	return p.LikeCount
}

func (p *InteractionItemsResp) GetCommentCount() (v int32) {
	return p.CommentCount
}

func (p *InteractionItemsResp) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *InteractionItemsResp) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}

func (p *InteractionItemsResp) GetDeletedAt() (v string) {
	return p.DeletedAt
}

func (p *InteractionItemsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InteractionItemsResp(%+v)", *p)
}

type LikeActionReq struct {
	AccessToken  string `thrift:"access_token,1" header:"Access-Token" json:"access_token"`
	RefreshToken string `thrift:"refresh_token,2" header:"Refresh-Token" json:"refresh_token"`
	VideoID      string `thrift:"video_id,3" form:"video_id" json:"video_id"`
	CommentID    string `thrift:"comment_id,4" form:"comment_id" json:"comment_id"`
	ActionType   string `thrift:"action_type,5" form:"action_type" json:"action_type"`
}

func NewLikeActionReq() *LikeActionReq {
	return &LikeActionReq{}
}

func (p *LikeActionReq) InitDefault() {
}

func (p *LikeActionReq) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *LikeActionReq) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *LikeActionReq) GetVideoID() (v string) {
	return p.VideoID
}

func (p *LikeActionReq) GetCommentID() (v string) {
	return p.CommentID
}

func (p *LikeActionReq) GetActionType() (v string) {
	return p.ActionType
}

func (p *LikeActionReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LikeActionReq(%+v)", *p)
}

type LikeActionResp struct {
	Base *base.BaseResp `thrift:"Base,1" form:"Base" json:"Base" query:"Base"`
}

func NewLikeActionResp() *LikeActionResp {
	return &LikeActionResp{}
}

func (p *LikeActionResp) InitDefault() {
}

var LikeActionResp_Base_DEFAULT *base.BaseResp

func (p *LikeActionResp) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return LikeActionResp_Base_DEFAULT
	}
	return p.Base
}

func (p *LikeActionResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *LikeActionResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LikeActionResp(%+v)", *p)
}

type LikeListReq struct {
	UserID       string `thrift:"user_id,1" json:"user_id" query:"user_id"`
	PageSize     int32  `thrift:"page_size,2" json:"page_size" query:"page_size"`
	PageNum      int32  `thrift:"page_num,3" json:"page_num" query:"page_num"`
	AccessToken  string `thrift:"access_token,4" header:"Access-Token" json:"access_token"`
	RefreshToken string `thrift:"refresh_token,5" header:"Refresh-Token" json:"refresh_token"`
}

func NewLikeListReq() *LikeListReq {
	return &LikeListReq{}
}

func (p *LikeListReq) InitDefault() {
}

func (p *LikeListReq) GetUserID() (v string) {
	return p.UserID
}

func (p *LikeListReq) GetPageSize() (v int32) {
	return p.PageSize
}

func (p *LikeListReq) GetPageNum() (v int32) {
	return p.PageNum
}

func (p *LikeListReq) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *LikeListReq) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *LikeListReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LikeListReq(%+v)", *p)
}

type LikeListResp struct {
	Base  *base.BaseResp          `thrift:"Base,1" form:"Base" json:"Base" query:"Base"`
	Items []*InteractionItemsResp `thrift:"Items,2,default,list<InteractionItemsResp>" form:"Items" json:"Items" query:"Items"`
}

func NewLikeListResp() *LikeListResp {
	return &LikeListResp{}
}

func (p *LikeListResp) InitDefault() {
}

var LikeListResp_Base_DEFAULT *base.BaseResp

func (p *LikeListResp) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return LikeListResp_Base_DEFAULT
	}
	return p.Base
}

func (p *LikeListResp) GetItems() (v []*InteractionItemsResp) {
	return p.Items
}

func (p *LikeListResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *LikeListResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LikeListResp(%+v)", *p)
}

type CommentPublishReq struct {
	VideoID   string `thrift:"video_id,3" form:"video_id" json:"video_id"`
	CommentID string `thrift:"comment_id,4" form:"comment_id" json:"comment_id"`
	Content   string `thrift:"content,5" form:"content" json:"content"`
}

func NewCommentPublishReq() *CommentPublishReq {
	return &CommentPublishReq{}
}

func (p *CommentPublishReq) InitDefault() {
}

func (p *CommentPublishReq) GetVideoID() (v string) {
	return p.VideoID
}

func (p *CommentPublishReq) GetCommentID() (v string) {
	return p.CommentID
}

func (p *CommentPublishReq) GetContent() (v string) {
	return p.Content
}

func (p *CommentPublishReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommentPublishReq(%+v)", *p)
}

type CommentPublishResp struct {
	Base *base.BaseResp `thrift:"Base,1" form:"Base" json:"Base" query:"Base"`
}

func NewCommentPublishResp() *CommentPublishResp {
	return &CommentPublishResp{}
}

func (p *CommentPublishResp) InitDefault() {
}

var CommentPublishResp_Base_DEFAULT *base.BaseResp

func (p *CommentPublishResp) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return CommentPublishResp_Base_DEFAULT
	}
	return p.Base
}

func (p *CommentPublishResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *CommentPublishResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommentPublishResp(%+v)", *p)
}

type CommentListReq struct {
	VideoID      string `thrift:"video_id,1" json:"video_id" query:"video_id"`
	CommentID    string `thrift:"comment_id,2" json:"comment_id" query:"comment_id"`
	PageSize     int32  `thrift:"page_size,3" json:"page_size" query:"page_size"`
	PageNum      int32  `thrift:"page_num,4" json:"page_num" query:"page_num"`
	AccessToken  string `thrift:"access_token,5" header:"Access-Token" json:"access_token"`
	RefreshToken string `thrift:"refresh_token,6" header:"Refresh-Token" json:"refresh_token"`
}

func NewCommentListReq() *CommentListReq {
	return &CommentListReq{}
}

func (p *CommentListReq) InitDefault() {
}

func (p *CommentListReq) GetVideoID() (v string) {
	return p.VideoID
}

func (p *CommentListReq) GetCommentID() (v string) {
	return p.CommentID
}

func (p *CommentListReq) GetPageSize() (v int32) {
	return p.PageSize
}

func (p *CommentListReq) GetPageNum() (v int32) {
	return p.PageNum
}

func (p *CommentListReq) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *CommentListReq) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *CommentListReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommentListReq(%+v)", *p)
}

type CommentListResp struct {
	Base  *base.BaseResp          `thrift:"Base,1" form:"Base" json:"Base" query:"Base"`
	Items []*InteractionItemsResp `thrift:"Items,2,default,list<InteractionItemsResp>" form:"Items" json:"Items" query:"Items"`
}

func NewCommentListResp() *CommentListResp {
	return &CommentListResp{}
}

func (p *CommentListResp) InitDefault() {
}

var CommentListResp_Base_DEFAULT *base.BaseResp

func (p *CommentListResp) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return CommentListResp_Base_DEFAULT
	}
	return p.Base
}

func (p *CommentListResp) GetItems() (v []*InteractionItemsResp) {
	return p.Items
}

func (p *CommentListResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *CommentListResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommentListResp(%+v)", *p)
}

type CommentDeleteReq struct {
	AccessToken  string `thrift:"access_token,1" header:"Access-Token" json:"access_token"`
	RefreshToken string `thrift:"refresh_token,2" header:"Refresh-Token" json:"refresh_token"`
	VideoID      string `thrift:"video_id,3" form:"video_id" json:"video_id"`
	CommentID    string `thrift:"comment_id,4" form:"comment_id" json:"comment_id"`
}

func NewCommentDeleteReq() *CommentDeleteReq {
	return &CommentDeleteReq{}
}

func (p *CommentDeleteReq) InitDefault() {
}

func (p *CommentDeleteReq) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *CommentDeleteReq) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *CommentDeleteReq) GetVideoID() (v string) {
	return p.VideoID
}

func (p *CommentDeleteReq) GetCommentID() (v string) {
	return p.CommentID
}

func (p *CommentDeleteReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommentDeleteReq(%+v)", *p)
}

type CommentDeleteResp struct {
	Base *base.BaseResp `thrift:"Base,1" form:"Base" json:"Base" query:"Base"`
}

func NewCommentDeleteResp() *CommentDeleteResp {
	return &CommentDeleteResp{}
}

func (p *CommentDeleteResp) InitDefault() {
}

var CommentDeleteResp_Base_DEFAULT *base.BaseResp

func (p *CommentDeleteResp) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return CommentDeleteResp_Base_DEFAULT
	}
	return p.Base
}

func (p *CommentDeleteResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *CommentDeleteResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommentDeleteResp(%+v)", *p)
}

type InteractionService interface {
	LikeAction(ctx context.Context, req *LikeActionReq) (r *LikeActionResp, err error)

	LikeList(ctx context.Context, req *LikeListReq) (r *LikeListResp, err error)

	CommentPublish(ctx context.Context, req *CommentPublishReq) (r *CommentPublishResp, err error)

	CommentList(ctx context.Context, req *CommentListReq) (r *CommentListResp, err error)

	CommentDelete(ctx context.Context, req *CommentDeleteReq) (r *CommentDeleteResp, err error)
}
