// Code generated by hertz generator.

package video

import (
	"context"
	"video_website/biz/middleware/jwt"
	"video_website/pkg/errno"
	"video_website/pkg/response"

	video "video_website/biz/model/video"
	videoService "video_website/biz/service/video"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

// Publish 投稿
// @router /videos/publish [POST]
func Publish(ctx context.Context, c *app.RequestContext) {
	var req video.VideoPublishReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	userID := jwt.GetUserID(ctx, c)
	if userID == "" {
		response.SendResponse(c, errno.Unauthorized, nil)
		return
	}

	if err := videoService.Publish(ctx, c, userID, req.Title, req.Description); err != nil {
		response.SendResponse(c, err, nil)
		return
	}

	response.SendResponse(c, errno.Success, nil)
}

// List 发布列表
// @router /videos/list [GET]
func List(ctx context.Context, c *app.RequestContext) {
	var req video.VideoListReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	items, total, err := videoService.List(ctx, req.UserID, req.PageNum, req.PageSize)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}

	type videoListData struct {
		Items []*video.VideoItemsResp `json:"items"`
		Total int32                   `json:"total"`
	}
	response.SendResponse(c, errno.Success, videoListData{
		Items: items,
		Total: total,
	})
}

// Popular 热门排行榜
// @router /videos/popular [GET]
func Popular(ctx context.Context, c *app.RequestContext) {
	var req video.VideoPopularReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	items, err := videoService.Popular(ctx, req.PageNum, req.PageSize)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}

	response.SendResponse(c, errno.Success, items)
}

// Search 搜索视频
// @router /videos/search [GET]
func Search(ctx context.Context, c *app.RequestContext) {
	var req video.VideoSearchReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	items, total, err := videoService.Search(ctx, req.Keywords, req.PageNum, req.PageSize)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}

	type videoSearchData struct {
		Items []*video.VideoItemsResp `json:"items"`
		Total int32                   `json:"total"`
	}
	response.SendResponse(c, errno.Success, videoSearchData{
		Items: items,
		Total: total,
	})
}
