// Code generated by hertz generator.

package video

import (
	"context"
	"os"
	"path/filepath"
	"time"
	"video_website/biz/dal/mysql"
	"video_website/biz/dal/mysql/entity"
	"video_website/biz/dal/redis"
	"video_website/pkg/errno"
	"video_website/pkg/jwt"
	"video_website/pkg/response"
	"video_website/pkg/utils"

	video "video_website/biz/model/video"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/common/json"
)

// Publish 投稿
// @router /videos/publish [POST]
func Publish(ctx context.Context, c *app.RequestContext) {
	var req video.VideoPublishReq
	if err := c.BindAndValidate(&req); err != nil {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	token := string(c.GetHeader("Access-Token"))
	if token == "" {
		response.SendResponse(c, errno.Unauthorized, nil)
		return
	}
	claims, err := jwt.ParseToken(token)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}
	userID := claims.UserID

	if len(req.Data) == 0 {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}
	fileName := utils.GenerateID() + ".mp4"
	filePath := filepath.Join("./static/videos", fileName)
	if err := os.WriteFile(filePath, req.Data, 0644); err != nil {
		hlog.CtxErrorf(ctx, "保存视频文件失败%v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}
	videoURL := "http:127.0.0.1:8888/static/videos/" + fileName

	now := time.Now()
	newVideo := &entity.Video{
		ID:          utils.GenerateID(),
		UserID:      userID,
		Title:       req.Title,
		Description: req.Description,
		VideoURL:    videoURL,
		CoverURL:    "",
		CreatedAt:   now,
		UpdatedAt:   now,
	}
	if err := mysql.CreateVideo(ctx, newVideo); err != nil {
		hlog.CtxErrorf(ctx, "创建视频失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}
}

// List 发布列表
// @router /videos/list [GET]
func List(ctx context.Context, c *app.RequestContext) {
	var req video.VideoListReq
	if err := c.BindAndValidate(&req); err != nil {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	videos, total, err := mysql.GetVideoByUserID(ctx, req.UserID, req.PageNum, req.PageSize)
	if err != nil {
		hlog.CtxErrorf(ctx, "查询视频列表失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}

	items := make([]*video.VideoItemsResp, 0, len(videos))
	for _, v := range videos {
		items = append(items, &video.VideoItemsResp{
			ID:           v.ID,
			UserID:       v.UserID,
			VideoURL:     v.VideoURL,
			CoverURL:     v.CoverURL,
			Title:        v.Title,
			Description:  v.Description,
			VisitCount:   int32(v.VisitCount),
			LikeCount:    int32(v.LikeCount),
			CommentCount: int32(v.CommentCount),
			CreatedAt:    v.CreatedAt.Format("2006-01-02 15:04:05"),
			UpdatedAt:    v.UpdatedAt.Format("2006-01-02 15:04:05"),
			DeletedAt:    "",
		})
	}

	resp := &video.VideoListResp{
		Items: items,
		Total: int32(total),
	}
	response.SendResponse(c, errno.Success, resp)
}

// Popular 热门排行榜
// @router /videos/popular [GET]
func Popular(ctx context.Context, c *app.RequestContext) {
	var req video.VideoPopularReq
	if err := c.BindAndValidate(&req); err != nil {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	cacheKey := "popular:videos"

	//从redis中获取缓存
	cached, err := redis.RDB.Get(ctx, cacheKey).Result()
	if err == nil {
		var allItems []*video.VideoItemsResp
		if json.Unmarshal([]byte(cached), &allItems) == nil {
			//内存分页
			start := (req.PageNum - 1) * req.PageSize
			end := start + req.PageSize
			if int(start) < len(allItems) {
				if int(end) > len(allItems) {
					end = int32(len(allItems))
				}
				resp := &video.VideoPopularResp{
					Items: allItems[start:end],
				}
				response.SendResponse(c, errno.Success, resp)
				return
			}
			//超出范围返回空列表
			response.SendResponse(c, errno.Success, &video.VideoPopularResp{Items: []*video.VideoItemsResp{}})
			return
		}
	}

	//缓存未命中，从数据库查询
	var videos []*entity.Video
	videos, err = mysql.GetPopularVideos(ctx, 1, 100)
	if err != nil {
		hlog.CtxErrorf(ctx, "查询热门视频失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}

	items := make([]*video.VideoItemsResp, 0, len(videos))
	for _, v := range videos {
		items = append(items, &video.VideoItemsResp{
			ID:           v.ID,
			UserID:       v.UserID,
			VideoURL:     v.VideoURL,
			CoverURL:     v.CoverURL,
			Title:        v.Title,
			Description:  v.Description,
			VisitCount:   int32(v.VisitCount),
			LikeCount:    int32(v.LikeCount),
			CommentCount: int32(v.CommentCount),
			CreatedAt:    v.CreatedAt.Format("2006-01-02 15:04:05"),
			UpdatedAt:    v.UpdatedAt.Format("2006-01-02 15:04:05"),
			DeletedAt:    "",
		})
	}

	//存入redis
	if jsonData, err := json.Marshal(items); err == nil {
		redis.RDB.Set(ctx, cacheKey, jsonData, 5*time.Minute)
	}

	start := (req.PageNum - 1) * req.PageSize
	end := start + req.PageSize
	if int(start) < len(videos) {
		if int(end) > len(videos) {
			end = int32(len(videos))
		}
		resp := &video.VideoPopularResp{
			Items: items[start:end],
		}
		response.SendResponse(c, errno.Success, resp)
		return
	}
	response.SendResponse(c, errno.Success, &video.VideoPopularResp{Items: []*video.VideoItemsResp{}})
}

// Search 搜索视频
// @router /videos/search [POST]
func Search(ctx context.Context, c *app.RequestContext) {
	var req video.VideoSearchReq
	if err := c.BindAndValidate(&req); err != nil {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	videos, total, err := mysql.SerachVideos(ctx, req.Keywords, req.PageNum, req.PageSize)
	if err != nil {
		hlog.CtxErrorf(ctx, "搜索视频失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}

	items := make([]*video.VideoItemsResp, 0, len(videos))
	for _, v := range videos {
		items = append(items, &video.VideoItemsResp{
			ID:           v.ID,
			UserID:       v.UserID,
			VideoURL:     v.VideoURL,
			CoverURL:     v.CoverURL,
			Title:        v.Title,
			Description:  v.Description,
			VisitCount:   int32(v.VisitCount),
			LikeCount:    int32(v.LikeCount),
			CommentCount: int32(v.CommentCount),
			CreatedAt:    v.CreatedAt.Format("2006-01-02 15:04:05"),
			UpdatedAt:    v.UpdatedAt.Format("2006-01-02 15:04:05"),
			DeletedAt:    "",
		})
	}

	resp := &video.VideoSearchResp{
		Items: items,
		Total: int32(total),
	}
	response.SendResponse(c, errno.Success, resp)
}
