// Code generated by hertz generator.

package video

import (
	"context"
	"io"
	"os"
	"path/filepath"
	"time"
	"video_website/biz/dal/mysql"
	"video_website/biz/dal/mysql/entity"
	"video_website/biz/dal/redis"
	"video_website/pkg/errno"
	"video_website/pkg/jwt"
	"video_website/pkg/response"
	"video_website/pkg/utils"

	video "video_website/biz/model/video"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/common/json"
)

// Publish 投稿
// @router /videos/publish [POST]
func Publish(ctx context.Context, c *app.RequestContext) {
	hlog.CtxInfof(ctx, "开始处理投稿请求")

	var req video.VideoPublishReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	file, err := c.FormFile("data")
	if err != nil {
		hlog.CtxErrorf(ctx, "获取文件表单失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}
	hlog.CtxInfof(ctx, "获取投稿文件成功, 文件名: %s, 大小: %d bytes", file.Filename, file.Size)

	src, err := file.Open()
	if err != nil {
		hlog.CtxErrorf(ctx, "打开文件失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}
	defer src.Close()

	dataBytes, err := io.ReadAll(src)
	if err != nil {
		hlog.CtxErrorf(ctx, "读取文件失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}
	req.Data = dataBytes

	token := string(c.GetHeader("Access-Token"))
	if token == "" {
		response.SendResponse(c, errno.Unauthorized, nil)
		return
	}
	claims, err := jwt.ParseToken(token)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}
	userID := claims.UserID
	hlog.CtxInfof(ctx, "投稿请求来自用户ID: %s", userID)

	if len(req.Data) == 0 {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}
	fileName := utils.GenerateID() + ".mp4"
	filePath := filepath.Join("./static/videos", fileName)
	if err := os.WriteFile(filePath, req.Data, 0644); err != nil {
		hlog.CtxErrorf(ctx, "保存视频文件失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}
	videoURL := "http://127.0.0.1:8888/static/videos/" + fileName // 修复 URL 格式
	hlog.CtxInfof(ctx, "视频文件保存成功, 路径: %s", filePath)

	now := time.Now()
	newVideo := &entity.Video{
		ID:          utils.GenerateID(),
		UserID:      userID,
		Title:       req.Title,
		Description: req.Description,
		VideoURL:    videoURL,
		CoverURL:    "",
		CreatedAt:   now,
		UpdatedAt:   now,
	}
	if err := mysql.CreateVideo(ctx, newVideo); err != nil {
		hlog.CtxErrorf(ctx, "创建视频记录失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}
	hlog.CtxInfof(ctx, "视频记录创建成功, 视频ID: %s", newVideo.ID)

	hlog.CtxInfof(ctx, "投稿处理完成, 用户ID: %s", userID)
	response.SendResponse(c, errno.Success, nil)
}

// List 发布列表
// @router /videos/list [GET]
func List(ctx context.Context, c *app.RequestContext) {
	var req video.VideoListReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}
	hlog.CtxInfof(ctx, "开始获取发布列表, 用户ID: %s, 页码: %d, 每页数量: %d", req.UserID, req.PageNum, req.PageSize)

	videos, total, err := mysql.GetVideoByUserID(ctx, req.UserID, req.PageNum, req.PageSize)
	if err != nil {
		hlog.CtxErrorf(ctx, "查询视频列表失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}
	hlog.CtxInfof(ctx, "查询到视频数量: %d, 总数: %d", len(videos), total)

	items := make([]*video.VideoItemsResp, 0, len(videos))
	for _, v := range videos {
		items = append(items, &video.VideoItemsResp{
			ID:           v.ID,
			UserID:       v.UserID,
			VideoURL:     v.VideoURL,
			CoverURL:     v.CoverURL,
			Title:        v.Title,
			Description:  v.Description,
			VisitCount:   int32(v.VisitCount),
			LikeCount:    int32(v.LikeCount),
			CommentCount: int32(v.CommentCount),
			CreatedAt:    v.CreatedAt.Format("2006-01-02 15:04:05"),
			UpdatedAt:    v.UpdatedAt.Format("2006-01-02 15:04:05"),
			DeletedAt:    "",
		})
	}

	type videoListData struct {
		Items []*video.VideoItemsResp `json:"items"`
		Total int32                   `json:"total"`
	}

	hlog.CtxInfof(ctx, "发布列表返回成功, 用户ID: %s", req.UserID)
	response.SendResponse(c, errno.Success, videoListData{
		Items: items,
		Total: int32(total),
	})
}

// Popular 热门排行榜
// @router /videos/popular [GET]
func Popular(ctx context.Context, c *app.RequestContext) {
	var req video.VideoPopularReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}
	hlog.CtxInfof(ctx, "开始获取热门视频, 页码: %d, 每页数量: %d", req.PageNum, req.PageSize)

	cacheKey := "popular:videos"

	// 从 Redis 获取缓存
	cached, err := redis.RDB.Get(ctx, cacheKey).Result()
	if err == nil {
		var allItems []*video.VideoItemsResp
		if json.Unmarshal([]byte(cached), &allItems) == nil {
			hlog.CtxInfof(ctx, "命中缓存, 热门视频总数: %d", len(allItems))
			// 内存分页
			start := (req.PageNum - 1) * req.PageSize
			end := start + req.PageSize
			if int(start) < len(allItems) {
				if int(end) > len(allItems) {
					end = int32(len(allItems))
				}
				hlog.CtxInfof(ctx, "从缓存返回热门视频, 数量: %d", end-start)
				response.SendResponse(c, errno.Success, allItems[start:end])
				return
			}
			hlog.CtxInfof(ctx, "缓存数据超出范围, 返回空列表")
			response.SendResponse(c, errno.Success, []*video.VideoItemsResp{})
			return
		}
	}

	// 缓存未命中，从数据库查询前100条热门视频
	hlog.CtxInfof(ctx, "缓存未命中, 从数据库查询热门视频")
	videos, err := mysql.GetPopularVideos(ctx, 1, 100)
	if err != nil {
		hlog.CtxErrorf(ctx, "查询热门视频失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}
	hlog.CtxInfof(ctx, "从数据库查询到热门视频数量: %d", len(videos))

	items := make([]*video.VideoItemsResp, 0, len(videos))
	for _, v := range videos {
		items = append(items, &video.VideoItemsResp{
			ID:           v.ID,
			UserID:       v.UserID,
			VideoURL:     v.VideoURL,
			CoverURL:     v.CoverURL,
			Title:        v.Title,
			Description:  v.Description,
			VisitCount:   int32(v.VisitCount),
			LikeCount:    int32(v.LikeCount),
			CommentCount: int32(v.CommentCount),
			CreatedAt:    v.CreatedAt.Format("2006-01-02 15:04:05"),
			UpdatedAt:    v.UpdatedAt.Format("2006-01-02 15:04:05"),
			DeletedAt:    "",
		})
	}

	// 存入 Redis 缓存
	if jsonData, err := json.Marshal(items); err == nil {
		redis.RDB.Set(ctx, cacheKey, jsonData, 5*time.Minute)
		hlog.CtxInfof(ctx, "热门视频缓存更新成功, 数量: %d", len(items))
	}

	start := (req.PageNum - 1) * req.PageSize
	end := start + req.PageSize
	if int(start) < len(items) {
		if int(end) > len(items) {
			end = int32(len(items))
		}
		hlog.CtxInfof(ctx, "返回热门视频, 数量: %d", end-start)
		response.SendResponse(c, errno.Success, items[start:end])
		return
	}
	hlog.CtxInfof(ctx, "热门视频列表为空")
	response.SendResponse(c, errno.Success, []*video.VideoItemsResp{})
}

// Search 搜索视频
// @router /videos/search [POST]
func Search(ctx context.Context, c *app.RequestContext) {
	var req video.VideoSearchReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}
	hlog.CtxInfof(ctx, "开始搜索视频, 关键词: %s, 页码: %d, 每页数量: %d", req.Keywords, req.PageNum, req.PageSize)

	videos, total, err := mysql.SearchVideos(ctx, req.Keywords, req.PageNum, req.PageSize) // 注意函数名拼写
	if err != nil {
		hlog.CtxErrorf(ctx, "搜索视频失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}
	hlog.CtxInfof(ctx, "搜索到视频数量: %d, 总数: %d", len(videos), total)

	items := make([]*video.VideoItemsResp, 0, len(videos))
	for _, v := range videos {
		items = append(items, &video.VideoItemsResp{
			ID:           v.ID,
			UserID:       v.UserID,
			VideoURL:     v.VideoURL,
			CoverURL:     v.CoverURL,
			Title:        v.Title,
			Description:  v.Description,
			VisitCount:   int32(v.VisitCount),
			LikeCount:    int32(v.LikeCount),
			CommentCount: int32(v.CommentCount),
			CreatedAt:    v.CreatedAt.Format("2006-01-02 15:04:05"),
			UpdatedAt:    v.UpdatedAt.Format("2006-01-02 15:04:05"),
			DeletedAt:    "",
		})
	}

	type videoSearchData struct {
		Items []*video.VideoItemsResp `json:"items"`
		Total int32                   `json:"total"`
	}

	hlog.CtxInfof(ctx, "搜索视频返回成功, 关键词: %s", req.Keywords)
	response.SendResponse(c, errno.Success, videoSearchData{
		Items: items,
		Total: int32(total),
	})
}
