server:
  address: ":8888"

mysql:
  dsn: "root:forEG0630@tcp(127.0.0.1:3306)/video_website?charset=utf8mb4&parseTime=True&loc=Local"

jwt:
  secret: "secret"

stitic:
  base_url: "http://localhost:8888/static"
  upload_dir: "./static"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0