// Code generated by hertz generator.

package user

import (
	"context"
	"video_website/biz/middleware/jwt"
	"video_website/pkg/errno"
	"video_website/pkg/response"

	user "video_website/biz/model/user"
	userService "video_website/biz/service/user"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

// Register 注册
// @router /user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var req user.UserRegisterReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	if err := userService.Register(ctx, req.Username, req.Password); err != nil {
		errno.Log(ctx, "注册失败", err)
		response.SendResponse(c, err, nil)
		return
	}

	response.SendResponse(c, errno.Success, nil)
}

// Login 登录
// @router /user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var req user.UserLoginReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	result, err := userService.Login(ctx, req.Username, req.Password, req.Code)
	if err != nil {
		errno.Log(ctx, "登录失败", err)
		response.SendResponse(c, err, nil)
		return
	}

	type loginData struct {
		Users        []*user.UserDataResp `json:"users"`
		AccessToken  string               `json:"access_token"`
		RefreshToken string               `json:"refresh_token"`
	}
	response.SendResponse(c, errno.Success, loginData{
		Users:        result.Users,
		AccessToken:  result.AccessToken,
		RefreshToken: result.RefreshToken,
	})
}

// Info 获取用户信息
// @router /user/info [GET]
func Info(ctx context.Context, c *app.RequestContext) {
	var req user.UserInfoReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	data, err := userService.Info(ctx, req.UserID)
	if err != nil {
		errno.Log(ctx, "获取用户信息失败", err)
		response.SendResponse(c, err, nil)
		return
	}

	response.SendResponse(c, errno.Success, data)
}

// UploadAvatar 上传头像
// @router /user/avatar/upload [PUT]
func UploadAvatar(ctx context.Context, c *app.RequestContext) {
	var req user.UserAvatarReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	userID := jwt.GetUserID(ctx, c)
	data, err := userService.UploadAvatar(ctx, c, userID)
	if err != nil {
		errno.Log(ctx, "上传头像失败", err)
		response.SendResponse(c, err, nil)
		return
	}

	response.SendResponse(c, errno.Success, data)
}

// Refresh 刷新令牌
// @router /user/refresh [POST]
func Refresh(ctx context.Context, c *app.RequestContext) {
	var req user.RefreshReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	result, err := userService.Refresh(ctx, req.RefreshToken)
	if err != nil {
		errno.Log(ctx, "刷新token失败", err)
		response.SendResponse(c, err, nil)
		return
	}

	type refreshData struct {
		AccessToken  string `json:"access_token"`
		RefreshToken string `json:"refresh_token"`
	}
	response.SendResponse(c, errno.Success, refreshData{
		AccessToken:  result.AccessToken,
		RefreshToken: result.RefreshToken,
	})
}

// GetMFA 获取MFA二维码
// @router /auth/mfa/qrcode [GET]
func GetMFA(ctx context.Context, c *app.RequestContext) {
	var req user.UserGetMFAReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	userID := jwt.GetUserID(ctx, c)
	result, err := userService.GetMFA(ctx, userID)
	if err != nil {
		errno.Log(ctx, "获取MFA二维码失败", err)
		response.SendResponse(c, err, nil)
		return
	}

	type mfaData struct {
		Secret string `json:"secret"`
		Qrcode string `json:"qrcode"`
	}
	response.SendResponse(c, errno.Success, mfaData{
		Secret: result.Secret,
		Qrcode: result.Qrcode,
	})
}

// BindMFA 绑定MFA
// @router /auth/mfa/bind [POST]
func BindMFA(ctx context.Context, c *app.RequestContext) {
	var req user.UserBindMFAReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	userID := jwt.GetUserID(ctx, c)
	if err := userService.BindMFA(ctx, userID, req.Code, req.Secret); err != nil {
		errno.Log(ctx, "绑定MFA失败", err)
		response.SendResponse(c, err, nil)
		return
	}

	response.SendResponse(c, errno.Success, nil)
}
