// Code generated by hertz generator.

package user

import (
	"context"
	"os"
	"time"
	"video_website/biz/dal/mysql"
	"video_website/biz/dal/mysql/entity"
	"video_website/biz/dal/redis"
	"video_website/biz/model/base"
	"video_website/pkg/bcrypt"
	"video_website/pkg/errno"
	"video_website/pkg/jwt"
	"video_website/pkg/response"
	"video_website/pkg/utils"

	user "video_website/biz/model/user"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	redis2 "github.com/redis/go-redis/v9"
)

// Register 注册
// @router /user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var req user.UserRegisterReq
	if err := c.BindAndValidate(&req); err != nil {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	exist, err := mysql.IsUserExist(ctx, req.Username)
	if err != nil {
		//hlog.CtxErrorf():记录带上下文的错误日志
		hlog.CtxErrorf(ctx, "检查用户名失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}
	if exist {
		response.SendResponse(c, errno.UsernameExists, nil)
		return
	}

	hashedPwd, err := bcrypt.HashPassword(req.Password)
	if err != nil {
		hlog.CtxErrorf(ctx, "密码加密失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}

	now := time.Now()
	newUser := &entity.User{
		ID:        utils.GenerateID(),
		Username:  req.Username,
		Password:  hashedPwd,
		AvatarURL: "https://default-avatar.com/default.png",
		CreatedAt: now,
		UpdatedAt: now,
		//DeletedAt为零值
	}
	if err := mysql.CreateUser(ctx, newUser); err != nil {
		hlog.CtxErrorf(ctx, "创建用户失败: &v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}

	response.SendResponse(c, errno.Success, nil)
}

// Login 登录
// @router /user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var req user.UserLoginReq
	if err := c.BindAndValidate(&req); err != nil {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	u, err := mysql.GetUserByUsername(ctx, req.Username)
	if err != nil {
		hlog.CtxErrorf(ctx, "查询用户失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}
	if u == nil {
		response.SendResponse(c, errno.UserNotExist, nil)
		return
	}

	if !bcrypt.CheckPasswordHash(req.Password, u.Password) {
		response.SendResponse(c, errno.PasswordError, nil)
		return
	}

	accessToken, err := jwt.GenerateAccessToken(u.ID)
	if err != nil {
		hlog.CtxErrorf(ctx, "生成access token失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}

	refreshToken, err := jwt.GenerateRefreshToken()
	if err != nil {
		hlog.CtxErrorf(ctx, "生成refresh token失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}

	//将refresh token存入Redis，设置七天过期
	redisKey := "refresh:" + refreshToken
	if err := redis.RDB.Set(ctx, redisKey, u.ID, 7*24*time.Hour).Err(); err != nil {
		hlog.CtxErrorf(ctx, "存储refresh token失败: %v", err)
		response.SendResponse(c, errno.RedisError, nil)
		return
	}

	data := []*user.UserDataResp{{
		ID:        u.ID,
		Username:  u.Username,
		AvatarURL: u.AvatarURL,
		CreatedAt: u.CreatedAt.Format("2006-01-02 15:04:05"),
		UpdatedAt: u.UpdatedAt.Format("2006-01-02 15:04:05"),
		DeletedAt: "",
	}}
	resp := &user.UserLoginResp{
		Base:         &base.BaseResp{Code: errno.Success.Code, Msg: errno.Success.Msg},
		Data:         data,
		AccessToken:  accessToken,
		RefreshToken: refreshToken,
	}
	response.SendResponse(c, errno.Success, resp)
}

// Info 获取用户信息
// @router /user/info [GET]
func Info(ctx context.Context, c *app.RequestContext) {
	var req user.UserInfoReq
	if err := c.BindAndValidate(&req); err != nil {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	u, err := mysql.GetUserByID(ctx, req.UserID)
	if err != nil {
		hlog.CtxErrorf(ctx, "查询用户失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}
	if u == nil {
		response.SendResponse(c, errno.UserNotExist, nil)
		return
	}

	data := []*user.UserDataResp{
		{
			ID:        u.ID,
			Username:  u.Username,
			AvatarURL: u.AvatarURL,
			CreatedAt: u.CreatedAt.Format("2006-01-02 15:04:05"),
			UpdatedAt: u.UpdatedAt.Format("2006-01-02 15:04:05"),
			DeletedAt: "",
		},
	}
	response.SendResponse(c, errno.Success, data)
}

// UploadAvatar 上传头像
// @router /user/avatar/upload [PUT]
func UploadAvatar(ctx context.Context, c *app.RequestContext) {
	var req user.UserAvatarReq
	if err := c.BindAndValidate(&req); err != nil {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	token := string(c.GetHeader("Access-token"))
	if token == "" {
		response.SendResponse(c, errno.Unauthorized, nil)
		return
	}
	claims, err := jwt.ParseToken(token)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}
	userID := claims.UserID

	//检验文件类型
	if len(req.Data) == 0 {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	fileName := userID + "_" + time.Now().Format("20060102150405") + ".jpg"
	filePath := "./static/avatars/" + fileName
	if err := os.WriteFile(filePath, req.Data, 0644); err != nil {
		hlog.CtxErrorf(ctx, "保存头像失败: %v", err)
		return
	}
	avatarURL := "http:127.0.0.1:8888/static/avatars/" + fileName

	if err := mysql.UpdateUserAvatar(ctx, userID, avatarURL); err != nil {
		hlog.CtxErrorf(ctx, "更新头像失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}

	u, err := mysql.GetUserByID(ctx, userID)
	if err != nil {
		hlog.CtxErrorf(ctx, "查询用户失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}
	data := []*user.UserDataResp{{
		ID:        u.ID,
		Username:  u.Username,
		AvatarURL: u.AvatarURL,
		CreatedAt: u.CreatedAt.Format("2006-01-02 15:04:05"),
		UpdatedAt: u.UpdatedAt.Format("2006-01-02 15:04:05"),
		DeletedAt: "",
	}}
	response.SendResponse(c, errno.Success, data)

}

// Refresh 刷新令牌
// @router /user/refresh [POST]
func Refresh(ctx context.Context, c *app.RequestContext) {
	var req user.RefreshReq
	if err := c.BindAndValidate(&req); err != nil {
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	redisKey := "refresh:" + req.RefreshToken
	userID, err := redis.RDB.Get(ctx, redisKey).Result()
	if err != redis2.Nil {
		response.SendResponse(c, errno.RedisError, nil)
		return
	} else if err != nil {
		hlog.CtxErrorf(ctx, "Redis错误: %v", err)
		response.SendResponse(c, errno.RedisError, nil)
		return
	}

	newAccessToken, err := jwt.GenerateAccessToken(userID)
	if err != nil {
		hlog.CtxErrorf(ctx, "生成access token失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}

	newRefreshToken, err := jwt.GenerateRefreshToken()
	if err != nil {
		hlog.CtxErrorf(ctx, "生成refresh token失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}

	//删除旧的 refresh token
	redis.RDB.Del(ctx, redisKey)
	//存储新的
	newKey := "refresh:" + newRefreshToken
	if err := redis.RDB.Set(ctx, newKey, userID, 7*24*time.Hour).Err(); err != nil {
		hlog.CtxErrorf(ctx, "存储refresh token失败: %v", err)
		response.SendResponse(c, errno.RedisError, nil)
		return
	}

	resp := &user.RefreshResp{
		Base: &base.BaseResp{
			Code: errno.Success.Code,
			Msg:  errno.Success.Msg,
		},
		AccessToken:  newAccessToken,
		RefreshToken: newRefreshToken,
	}
	response.SendResponse(c, errno.Success, resp)
}
