// Code generated by hertz generator.

package user

import (
	"context"
	"video_website/biz/middleware/jwt"
	"video_website/pkg/errno"
	"video_website/pkg/response"

	user "video_website/biz/model/user"
	userService "video_website/biz/service/user"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

// Register 注册
// @router /user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var req user.UserRegisterReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	if err := userService.Register(ctx, req.Username, req.Password); err != nil {
		response.SendResponse(c, err, nil)
		return
	}

	response.SendResponse(c, errno.Success, nil)
}

// Login 登录
// @router /user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var req user.UserLoginReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	result, err := userService.Login(ctx, req.Username, req.Password)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}

	type loginData struct {
		Users        []*user.UserDataResp `json:"users"`
		AccessToken  string               `json:"access_token"`
		RefreshToken string               `json:"refresh_token"`
	}
	response.SendResponse(c, errno.Success, loginData{
		Users:        result.Users,
		AccessToken:  result.AccessToken,
		RefreshToken: result.RefreshToken,
	})
}

// Info 获取用户信息
// @router /user/info [GET]
func Info(ctx context.Context, c *app.RequestContext) {
	var req user.UserInfoReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	data, err := userService.Info(ctx, req.UserID)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}

	response.SendResponse(c, errno.Success, data)
}

// UploadAvatar 上传头像
// @router /user/avatar/upload [PUT]
func UploadAvatar(ctx context.Context, c *app.RequestContext) {
	var req user.UserAvatarReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	userID := jwt.GetUserID(ctx, c)
	if userID == "" {
		response.SendResponse(c, errno.Unauthorized, nil)
		return
	}

	data, err := userService.UploadAvatar(ctx, c, userID)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}

	response.SendResponse(c, errno.Success, data)
}

// Refresh 刷新令牌
// @router /user/refresh [POST]
func Refresh(ctx context.Context, c *app.RequestContext) {
	var req user.RefreshReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	result, err := userService.Refresh(ctx, req.RefreshToken)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}

	type refreshData struct {
		AccessToken  string `json:"access_token"`
		RefreshToken string `json:"refresh_token"`
	}
	response.SendResponse(c, errno.Success, refreshData{
		AccessToken:  result.AccessToken,
		RefreshToken: result.RefreshToken,
	})
}
