// Code generated by hertz generator.

package user

import (
	"context"
	"io"
	"os"
	"time"
	"video_website/pkg/errno"
	"video_website/pkg/jwt"
	"video_website/pkg/response"

	user "video_website/biz/model/user"
	userService "video_website/biz/service/user"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

// Register 注册
// @router /user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var req user.UserRegisterReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	if err := userService.Register(ctx, req.Username, req.Password); err != nil {
		response.SendResponse(c, err, nil)
		return
	}

	response.SendResponse(c, errno.Success, nil)
}

// Login 登录
// @router /user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var req user.UserLoginReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	result, err := userService.Login(ctx, req.Username, req.Password)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}

	type loginData struct {
		Users        []*user.UserDataResp `json:"users"`
		AccessToken  string               `json:"access_token"`
		RefreshToken string               `json:"refresh_token"`
	}
	response.SendResponse(c, errno.Success, loginData{
		Users:        result.Users,
		AccessToken:  result.AccessToken,
		RefreshToken: result.RefreshToken,
	})
}

// Info 获取用户信息
// @router /user/info [GET]
func Info(ctx context.Context, c *app.RequestContext) {
	var req user.UserInfoReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	data, err := userService.Info(ctx, req.UserID)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}

	response.SendResponse(c, errno.Success, data)
}

// UploadAvatar 上传头像
// @router /user/avatar/upload [PUT]
func UploadAvatar(ctx context.Context, c *app.RequestContext) {
	var req user.UserAvatarReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	file, err := c.FormFile("data")
	if err != nil {
		hlog.CtxErrorf(ctx, "获取文件表单失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	src, err := file.Open()
	if err != nil {
		hlog.CtxErrorf(ctx, "打开文件失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}
	defer src.Close()

	dataBytes, err := io.ReadAll(src)
	if err != nil {
		hlog.CtxErrorf(ctx, "读取文件失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}
	hlog.CtxInfof(ctx, "获取头像文件成功, 文件名: %s, 大小: %d bytes", file.Filename, file.Size)

	token := string(c.GetHeader("Access-token"))
	if token == "" {
		response.SendResponse(c, errno.Unauthorized, nil)
		return
	}
	claims, err := jwt.ParseToken(token)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}
	userID := claims.UserID

	fileName := userID + "_" + time.Now().Format("20060102150405") + ".jpg"
	filePath := "./static/avatars/" + fileName
	if err := os.WriteFile(filePath, dataBytes, 0644); err != nil {
		hlog.CtxErrorf(ctx, "保存头像失败: %v", err)
		response.SendResponse(c, errno.DBError, nil)
		return
	}

	data, err := userService.UploadAvatar(ctx, userID, dataBytes)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}

	response.SendResponse(c, errno.Success, data)
}

// Refresh 刷新令牌
// @router /user/refresh [POST]
func Refresh(ctx context.Context, c *app.RequestContext) {
	var req user.RefreshReq
	if err := c.BindAndValidate(&req); err != nil {
		hlog.CtxErrorf(ctx, "绑定并验证失败: %v", err)
		response.SendResponse(c, errno.ParamError, nil)
		return
	}

	result, err := userService.Refresh(ctx, req.RefreshToken)
	if err != nil {
		response.SendResponse(c, err, nil)
		return
	}

	type refreshData struct {
		AccessToken  string `json:"access_token"`
		RefreshToken string `json:"refresh_token"`
	}
	response.SendResponse(c, errno.Success, refreshData{
		AccessToken:  result.AccessToken,
		RefreshToken: result.RefreshToken,
	})
}
