// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package user

import (
	"context"
	"fmt"
	"video_website/biz/model/base"
)

type UserDataResp struct {
	ID        string `thrift:"id,1" form:"id" json:"id" query:"id"`
	Username  string `thrift:"username,2" form:"username" json:"username" query:"username"`
	AvatarURL string `thrift:"avatar_url,3" form:"avatar_url" json:"avatar_url" query:"avatar_url"`
	CreatedAt string `thrift:"created_at,4" form:"created_at" json:"created_at" query:"created_at"`
	UpdatedAt string `thrift:"updated_at,5" form:"updated_at" json:"updated_at" query:"updated_at"`
	DeletedAt string `thrift:"deleted_at,6" form:"deleted_at" json:"deleted_at" query:"deleted_at"`
}

func NewUserDataResp() *UserDataResp {
	return &UserDataResp{}
}

func (p *UserDataResp) InitDefault() {
}

func (p *UserDataResp) GetID() (v string) {
	return p.ID
}

func (p *UserDataResp) GetUsername() (v string) {
	return p.Username
}

func (p *UserDataResp) GetAvatarURL() (v string) {
	return p.AvatarURL
}

func (p *UserDataResp) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *UserDataResp) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}

func (p *UserDataResp) GetDeletedAt() (v string) {
	return p.DeletedAt
}

func (p *UserDataResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserDataResp(%+v)", *p)
}

type UserRegisterReq struct {
	Username string `thrift:"username,1" form:"username" json:"username"`
	Password string `thrift:"password,2" form:"password" json:"password"`
}

func NewUserRegisterReq() *UserRegisterReq {
	return &UserRegisterReq{}
}

func (p *UserRegisterReq) InitDefault() {
}

func (p *UserRegisterReq) GetUsername() (v string) {
	return p.Username
}

func (p *UserRegisterReq) GetPassword() (v string) {
	return p.Password
}

func (p *UserRegisterReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserRegisterReq(%+v)", *p)
}

type UserRegisterResp struct {
	Base *base.BaseResp `thrift:"Base,1" form:"Base" json:"Base" query:"Base"`
}

func NewUserRegisterResp() *UserRegisterResp {
	return &UserRegisterResp{}
}

func (p *UserRegisterResp) InitDefault() {
}

var UserRegisterResp_Base_DEFAULT *base.BaseResp

func (p *UserRegisterResp) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return UserRegisterResp_Base_DEFAULT
	}
	return p.Base
}

func (p *UserRegisterResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *UserRegisterResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserRegisterResp(%+v)", *p)
}

type UserLoginReq struct {
	Username string `thrift:"username,1" form:"username" json:"username"`
	Password string `thrift:"password,2" form:"password" json:"password"`
	Code     string `thrift:"code,3" form:"code" json:"code"`
}

func NewUserLoginReq() *UserLoginReq {
	return &UserLoginReq{}
}

func (p *UserLoginReq) InitDefault() {
}

func (p *UserLoginReq) GetUsername() (v string) {
	return p.Username
}

func (p *UserLoginReq) GetPassword() (v string) {
	return p.Password
}

func (p *UserLoginReq) GetCode() (v string) {
	return p.Code
}

func (p *UserLoginReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserLoginReq(%+v)", *p)
}

type UserLoginResp struct {
	Base         *base.BaseResp  `thrift:"Base,1" form:"Base" json:"Base" query:"Base"`
	Data         []*UserDataResp `thrift:"Data,2,default,list<UserDataResp>" form:"Data" json:"Data" query:"Data"`
	AccessToken  string          `thrift:"access_token,3" form:"access_token" json:"access_token" query:"access_token"`
	RefreshToken string          `thrift:"refresh_token,4" form:"refresh_token" json:"refresh_token" query:"refresh_token"`
}

func NewUserLoginResp() *UserLoginResp {
	return &UserLoginResp{}
}

func (p *UserLoginResp) InitDefault() {
}

var UserLoginResp_Base_DEFAULT *base.BaseResp

func (p *UserLoginResp) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return UserLoginResp_Base_DEFAULT
	}
	return p.Base
}

func (p *UserLoginResp) GetData() (v []*UserDataResp) {
	return p.Data
}

func (p *UserLoginResp) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *UserLoginResp) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *UserLoginResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *UserLoginResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserLoginResp(%+v)", *p)
}

type RefreshReq struct {
	RefreshToken string `thrift:"refresh_token,1" form:"refresh_token" json:"refresh_token"`
}

func NewRefreshReq() *RefreshReq {
	return &RefreshReq{}
}

func (p *RefreshReq) InitDefault() {
}

func (p *RefreshReq) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *RefreshReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefreshReq(%+v)", *p)
}

type RefreshResp struct {
	Base         *base.BaseResp `thrift:"Base,1" form:"Base" json:"Base" query:"Base"`
	AccessToken  string         `thrift:"access_token,2" form:"access_token" json:"access_token" query:"access_token"`
	RefreshToken string         `thrift:"refresh_token,3" form:"refresh_token" json:"refresh_token" query:"refresh_token"`
}

func NewRefreshResp() *RefreshResp {
	return &RefreshResp{}
}

func (p *RefreshResp) InitDefault() {
}

var RefreshResp_Base_DEFAULT *base.BaseResp

func (p *RefreshResp) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return RefreshResp_Base_DEFAULT
	}
	return p.Base
}

func (p *RefreshResp) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *RefreshResp) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *RefreshResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *RefreshResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefreshResp(%+v)", *p)
}

type UserInfoReq struct {
	UserID       string `thrift:"user_id,1" json:"user_id" query:"user_id"`
	AccessToken  string `thrift:"access_token,2" header:"Access-Token" json:"access_token"`
	RefreshToken string `thrift:"refresh_token,3" header:"Refresh-Token" json:"refresh_token"`
}

func NewUserInfoReq() *UserInfoReq {
	return &UserInfoReq{}
}

func (p *UserInfoReq) InitDefault() {
}

func (p *UserInfoReq) GetUserID() (v string) {
	return p.UserID
}

func (p *UserInfoReq) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *UserInfoReq) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *UserInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserInfoReq(%+v)", *p)
}

type UserInfoResp struct {
	Base *base.BaseResp  `thrift:"Base,1" form:"Base" json:"Base" query:"Base"`
	Data []*UserDataResp `thrift:"Data,2,default,list<UserDataResp>" form:"Data" json:"Data" query:"Data"`
}

func NewUserInfoResp() *UserInfoResp {
	return &UserInfoResp{}
}

func (p *UserInfoResp) InitDefault() {
}

var UserInfoResp_Base_DEFAULT *base.BaseResp

func (p *UserInfoResp) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return UserInfoResp_Base_DEFAULT
	}
	return p.Base
}

func (p *UserInfoResp) GetData() (v []*UserDataResp) {
	return p.Data
}

func (p *UserInfoResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *UserInfoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserInfoResp(%+v)", *p)
}

type UserAvatarReq struct {
	AccessToken  string `thrift:"access_token,1" header:"Access-Token" json:"access_token"`
	RefreshToken string `thrift:"refresh_token,2" header:"Refresh-Token" json:"refresh_token"`
	Data         []byte `thrift:"data,3" form:"data" json:"data"`
}

func NewUserAvatarReq() *UserAvatarReq {
	return &UserAvatarReq{}
}

func (p *UserAvatarReq) InitDefault() {
}

func (p *UserAvatarReq) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *UserAvatarReq) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *UserAvatarReq) GetData() (v []byte) {
	return p.Data
}

func (p *UserAvatarReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserAvatarReq(%+v)", *p)
}

type UserAvatarResp struct {
	Base *base.BaseResp  `thrift:"Base,1" form:"Base" json:"Base" query:"Base"`
	Data []*UserDataResp `thrift:"Data,2,default,list<UserDataResp>" form:"Data" json:"Data" query:"Data"`
}

func NewUserAvatarResp() *UserAvatarResp {
	return &UserAvatarResp{}
}

func (p *UserAvatarResp) InitDefault() {
}

var UserAvatarResp_Base_DEFAULT *base.BaseResp

func (p *UserAvatarResp) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return UserAvatarResp_Base_DEFAULT
	}
	return p.Base
}

func (p *UserAvatarResp) GetData() (v []*UserDataResp) {
	return p.Data
}

func (p *UserAvatarResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *UserAvatarResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserAvatarResp(%+v)", *p)
}

type UserService interface {
	Register(ctx context.Context, req *UserRegisterReq) (r *UserRegisterResp, err error)

	Login(ctx context.Context, req *UserLoginReq) (r *UserLoginResp, err error)

	Info(ctx context.Context, req *UserInfoReq) (r *UserInfoResp, err error)

	UploadAvatar(ctx context.Context, req *UserAvatarReq) (r *UserAvatarResp, err error)

	Refresh(ctx context.Context, req *RefreshReq) (r *RefreshResp, err error)
}
