// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package video

import (
	"context"
	"fmt"
	"video_website/biz/model/base"
)

type VideoItemsResp struct {
	ID           string `thrift:"id,1" form:"id" json:"id" query:"id"`
	UserID       string `thrift:"user_id,2" form:"user_id" json:"user_id" query:"user_id"`
	VideoURL     string `thrift:"video_url,3" form:"video_url" json:"video_url" query:"video_url"`
	CoverURL     string `thrift:"cover_url,4" form:"cover_url" json:"cover_url" query:"cover_url"`
	Title        string `thrift:"title,5" form:"title" json:"title" query:"title"`
	Description  string `thrift:"description,6" form:"description" json:"description" query:"description"`
	VisitCount   int32  `thrift:"visit_count,7" form:"visit_count" json:"visit_count" query:"visit_count"`
	LikeCount    int32  `thrift:"like_count,8" form:"like_count" json:"like_count" query:"like_count"`
	CommentCount int32  `thrift:"comment_count,9" form:"comment_count" json:"comment_count" query:"comment_count"`
	CreatedAt    string `thrift:"created_at,10" form:"created_at" json:"created_at" query:"created_at"`
	UpdatedAt    string `thrift:"updated_at,11" form:"updated_at" json:"updated_at" query:"updated_at"`
	DeletedAt    string `thrift:"deleted_at,12" form:"deleted_at" json:"deleted_at" query:"deleted_at"`
}

func NewVideoItemsResp() *VideoItemsResp {
	return &VideoItemsResp{}
}

func (p *VideoItemsResp) InitDefault() {
}

func (p *VideoItemsResp) GetID() (v string) {
	return p.ID
}

func (p *VideoItemsResp) GetUserID() (v string) {
	return p.UserID
}

func (p *VideoItemsResp) GetVideoURL() (v string) {
	return p.VideoURL
}

func (p *VideoItemsResp) GetCoverURL() (v string) {
	return p.CoverURL
}

func (p *VideoItemsResp) GetTitle() (v string) {
	return p.Title
}

func (p *VideoItemsResp) GetDescription() (v string) {
	return p.Description
}

func (p *VideoItemsResp) GetVisitCount() (v int32) {
	return p.VisitCount
}

func (p *VideoItemsResp) GetLikeCount() (v int32) {
	return p.LikeCount
}

func (p *VideoItemsResp) GetCommentCount() (v int32) {
	return p.CommentCount
}

func (p *VideoItemsResp) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *VideoItemsResp) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}

func (p *VideoItemsResp) GetDeletedAt() (v string) {
	return p.DeletedAt
}

func (p *VideoItemsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoItemsResp(%+v)", *p)
}

type VideoPublishReq struct {
	AccessToken  string `thrift:"access_token,1" header:"Access-Token" json:"access_token"`
	RefreshToken string `thrift:"refresh_token,2" header:"Refresh-Token" json:"refresh_token"`
	Data         []byte `thrift:"data,3" form:"data" json:"data"`
	Title        string `thrift:"title,4" form:"title" json:"title"`
	Description  string `thrift:"description,5" form:"description" json:"description"`
}

func NewVideoPublishReq() *VideoPublishReq {
	return &VideoPublishReq{}
}

func (p *VideoPublishReq) InitDefault() {
}

func (p *VideoPublishReq) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *VideoPublishReq) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *VideoPublishReq) GetData() (v []byte) {
	return p.Data
}

func (p *VideoPublishReq) GetTitle() (v string) {
	return p.Title
}

func (p *VideoPublishReq) GetDescription() (v string) {
	return p.Description
}

func (p *VideoPublishReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoPublishReq(%+v)", *p)
}

type VideoPublishResp struct {
	Base *base.BaseResp `thrift:"Base,1" form:"Base" json:"Base" query:"Base"`
}

func NewVideoPublishResp() *VideoPublishResp {
	return &VideoPublishResp{}
}

func (p *VideoPublishResp) InitDefault() {
}

var VideoPublishResp_Base_DEFAULT *base.BaseResp

func (p *VideoPublishResp) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return VideoPublishResp_Base_DEFAULT
	}
	return p.Base
}

func (p *VideoPublishResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *VideoPublishResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoPublishResp(%+v)", *p)
}

type VideoListReq struct {
	UserID       string `thrift:"user_id,1" json:"user_id" query:"user_id"`
	PageNum      int32  `thrift:"page_num,2" json:"page_num" query:"page_num"`
	PageSize     int32  `thrift:"page_size,3" json:"page_size" query:"page_size"`
	AccessToken  string `thrift:"access_token,4" header:"Access-Token" json:"access_token"`
	RefreshToken string `thrift:"refresh_token,5" header:"Refresh-Token" json:"refresh_token"`
}

func NewVideoListReq() *VideoListReq {
	return &VideoListReq{}
}

func (p *VideoListReq) InitDefault() {
}

func (p *VideoListReq) GetUserID() (v string) {
	return p.UserID
}

func (p *VideoListReq) GetPageNum() (v int32) {
	return p.PageNum
}

func (p *VideoListReq) GetPageSize() (v int32) {
	return p.PageSize
}

func (p *VideoListReq) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *VideoListReq) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *VideoListReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoListReq(%+v)", *p)
}

type VideoListResp struct {
	Base  *base.BaseResp    `thrift:"Base,1" form:"Base" json:"Base" query:"Base"`
	Items []*VideoItemsResp `thrift:"Items,2,default,list<VideoItemsResp>" form:"Items" json:"Items" query:"Items"`
	Total int32             `thrift:"total,3" form:"total" json:"total" query:"total"`
}

func NewVideoListResp() *VideoListResp {
	return &VideoListResp{}
}

func (p *VideoListResp) InitDefault() {
}

var VideoListResp_Base_DEFAULT *base.BaseResp

func (p *VideoListResp) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return VideoListResp_Base_DEFAULT
	}
	return p.Base
}

func (p *VideoListResp) GetItems() (v []*VideoItemsResp) {
	return p.Items
}

func (p *VideoListResp) GetTotal() (v int32) {
	return p.Total
}

func (p *VideoListResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *VideoListResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoListResp(%+v)", *p)
}

type VideoPopularReq struct {
	PageNum      int32  `thrift:"page_num,1" json:"page_num" query:"page_num"`
	PageSize     int32  `thrift:"page_size,2" json:"page_size" query:"page_size"`
	AccessToken  string `thrift:"access_token,3" header:"Access-Token" json:"access_token"`
	RefreshToken string `thrift:"refresh_token,4" header:"Refresh-Token" json:"refresh_token"`
}

func NewVideoPopularReq() *VideoPopularReq {
	return &VideoPopularReq{}
}

func (p *VideoPopularReq) InitDefault() {
}

func (p *VideoPopularReq) GetPageNum() (v int32) {
	return p.PageNum
}

func (p *VideoPopularReq) GetPageSize() (v int32) {
	return p.PageSize
}

func (p *VideoPopularReq) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *VideoPopularReq) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *VideoPopularReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoPopularReq(%+v)", *p)
}

type VideoPopularResp struct {
	Base  *base.BaseResp    `thrift:"Base,1" form:"Base" json:"Base" query:"Base"`
	Items []*VideoItemsResp `thrift:"Items,2,default,list<VideoItemsResp>" form:"Items" json:"Items" query:"Items"`
}

func NewVideoPopularResp() *VideoPopularResp {
	return &VideoPopularResp{}
}

func (p *VideoPopularResp) InitDefault() {
}

var VideoPopularResp_Base_DEFAULT *base.BaseResp

func (p *VideoPopularResp) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return VideoPopularResp_Base_DEFAULT
	}
	return p.Base
}

func (p *VideoPopularResp) GetItems() (v []*VideoItemsResp) {
	return p.Items
}

func (p *VideoPopularResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *VideoPopularResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoPopularResp(%+v)", *p)
}

type VideoSearchReq struct {
	AccessToken  string `thrift:"access_token,1" header:"Access-Token" json:"access_token"`
	RefreshToken string `thrift:"refresh_token,2" header:"Refresh-Token" json:"refresh_token"`
	Keywords     string `thrift:"keywords,3" form:"keywords" json:"keywords"`
	PageNum      int32  `thrift:"page_num,4" form:"page_num" json:"page_num"`
	PageSize     int32  `thrift:"page_size,5" form:"page_size" json:"page_size"`
	FromDate     int32  `thrift:"from_date,6" form:"from_date" json:"from_date"`
	ToDate       int32  `thrift:"to_date,7" form:"to_date" json:"to_date"`
	Username     string `thrift:"username,8" form:"username" json:"username"`
}

func NewVideoSearchReq() *VideoSearchReq {
	return &VideoSearchReq{}
}

func (p *VideoSearchReq) InitDefault() {
}

func (p *VideoSearchReq) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *VideoSearchReq) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *VideoSearchReq) GetKeywords() (v string) {
	return p.Keywords
}

func (p *VideoSearchReq) GetPageNum() (v int32) {
	return p.PageNum
}

func (p *VideoSearchReq) GetPageSize() (v int32) {
	return p.PageSize
}

func (p *VideoSearchReq) GetFromDate() (v int32) {
	return p.FromDate
}

func (p *VideoSearchReq) GetToDate() (v int32) {
	return p.ToDate
}

func (p *VideoSearchReq) GetUsername() (v string) {
	return p.Username
}

func (p *VideoSearchReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoSearchReq(%+v)", *p)
}

type VideoSearchResp struct {
	Base  *base.BaseResp    `thrift:"Base,1" form:"Base" json:"Base" query:"Base"`
	Items []*VideoItemsResp `thrift:"Items,2,default,list<VideoItemsResp>" form:"Items" json:"Items" query:"Items"`
	Total int32             `thrift:"total,3" form:"total" json:"total" query:"total"`
}

func NewVideoSearchResp() *VideoSearchResp {
	return &VideoSearchResp{}
}

func (p *VideoSearchResp) InitDefault() {
}

var VideoSearchResp_Base_DEFAULT *base.BaseResp

func (p *VideoSearchResp) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return VideoSearchResp_Base_DEFAULT
	}
	return p.Base
}

func (p *VideoSearchResp) GetItems() (v []*VideoItemsResp) {
	return p.Items
}

func (p *VideoSearchResp) GetTotal() (v int32) {
	return p.Total
}

func (p *VideoSearchResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *VideoSearchResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoSearchResp(%+v)", *p)
}

type VideoService interface {
	Publish(ctx context.Context, req *VideoPublishReq) (r *VideoPublishResp, err error)

	List(ctx context.Context, req *VideoListReq) (r *VideoListResp, err error)

	Popular(ctx context.Context, req *VideoPopularReq) (r *VideoPopularResp, err error)

	Search(ctx context.Context, req *VideoSearchReq) (r *VideoSearchResp, err error)
}
