// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package social

import (
	"context"
	"fmt"
	"video_website/biz/model/base"
)

type SocialItemsResp struct {
	ID        string `thrift:"id,1" form:"id" json:"id" query:"id"`
	Username  string `thrift:"username,2" form:"username" json:"username" query:"username"`
	AvatarURL string `thrift:"avatar_url,3" form:"avatar_url" json:"avatar_url" query:"avatar_url"`
}

func NewSocialItemsResp() *SocialItemsResp {
	return &SocialItemsResp{}
}

func (p *SocialItemsResp) InitDefault() {
}

func (p *SocialItemsResp) GetID() (v string) {
	return p.ID
}

func (p *SocialItemsResp) GetUsername() (v string) {
	return p.Username
}

func (p *SocialItemsResp) GetAvatarURL() (v string) {
	return p.AvatarURL
}

func (p *SocialItemsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SocialItemsResp(%+v)", *p)
}

type RelationActionReq struct {
	AccessToken  string `thrift:"access_token,1" header:"Access-Token" json:"access_token"`
	RefreshToken string `thrift:"refresh_token,2" header:"Refresh-Token" json:"refresh_token"`
	ToUserID     string `thrift:"to_user_id,3" form:"to_user_id" json:"to_user_id"`
	ActionType   int32  `thrift:"action_type,4" form:"action_type" json:"action_type"`
}

func NewRelationActionReq() *RelationActionReq {
	return &RelationActionReq{}
}

func (p *RelationActionReq) InitDefault() {
}

func (p *RelationActionReq) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *RelationActionReq) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *RelationActionReq) GetToUserID() (v string) {
	return p.ToUserID
}

func (p *RelationActionReq) GetActionType() (v int32) {
	return p.ActionType
}

func (p *RelationActionReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RelationActionReq(%+v)", *p)
}

type RelationActionResp struct {
	Base *base.BaseResp `thrift:"Base,1" form:"Base" json:"Base" query:"Base"`
}

func NewRelationActionResp() *RelationActionResp {
	return &RelationActionResp{}
}

func (p *RelationActionResp) InitDefault() {
}

var RelationActionResp_Base_DEFAULT *base.BaseResp

func (p *RelationActionResp) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return RelationActionResp_Base_DEFAULT
	}
	return p.Base
}

func (p *RelationActionResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *RelationActionResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RelationActionResp(%+v)", *p)
}

type FollowingListReq struct {
	UserID       string `thrift:"user_id,1" json:"user_id" query:"user_id"`
	PageNum      int32  `thrift:"page_num,2" json:"page_num" query:"page_num"`
	PageSize     int32  `thrift:"page_size,3" json:"page_size" query:"page_size"`
	AccessToken  string `thrift:"access_token,4" header:"Access-Token" json:"access_token"`
	RefreshToken string `thrift:"refresh_token,5" header:"Refresh-Token" json:"refresh_token"`
}

func NewFollowingListReq() *FollowingListReq {
	return &FollowingListReq{}
}

func (p *FollowingListReq) InitDefault() {
}

func (p *FollowingListReq) GetUserID() (v string) {
	return p.UserID
}

func (p *FollowingListReq) GetPageNum() (v int32) {
	return p.PageNum
}

func (p *FollowingListReq) GetPageSize() (v int32) {
	return p.PageSize
}

func (p *FollowingListReq) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *FollowingListReq) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *FollowingListReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FollowingListReq(%+v)", *p)
}

type FollowingListResp struct {
	Base  *base.BaseResp     `thrift:"Base,1" form:"Base" json:"Base" query:"Base"`
	Items []*SocialItemsResp `thrift:"Items,2,default,list<SocialItemsResp>" form:"Items" json:"Items" query:"Items"`
	Total int32              `thrift:"total,3" form:"total" json:"total" query:"total"`
}

func NewFollowingListResp() *FollowingListResp {
	return &FollowingListResp{}
}

func (p *FollowingListResp) InitDefault() {
}

var FollowingListResp_Base_DEFAULT *base.BaseResp

func (p *FollowingListResp) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return FollowingListResp_Base_DEFAULT
	}
	return p.Base
}

func (p *FollowingListResp) GetItems() (v []*SocialItemsResp) {
	return p.Items
}

func (p *FollowingListResp) GetTotal() (v int32) {
	return p.Total
}

func (p *FollowingListResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *FollowingListResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FollowingListResp(%+v)", *p)
}

type FollowerListReq struct {
	UserID       string `thrift:"user_id,1" json:"user_id" query:"user_id"`
	PageNum      int32  `thrift:"page_num,2" json:"page_num" query:"page_num"`
	PageSize     int32  `thrift:"page_size,3" json:"page_size" query:"page_size"`
	AccessToken  string `thrift:"access_token,4" header:"Access-Token" json:"access_token"`
	RefreshToken string `thrift:"refresh_token,5" header:"Refresh-Token" json:"refresh_token"`
}

func NewFollowerListReq() *FollowerListReq {
	return &FollowerListReq{}
}

func (p *FollowerListReq) InitDefault() {
}

func (p *FollowerListReq) GetUserID() (v string) {
	return p.UserID
}

func (p *FollowerListReq) GetPageNum() (v int32) {
	return p.PageNum
}

func (p *FollowerListReq) GetPageSize() (v int32) {
	return p.PageSize
}

func (p *FollowerListReq) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *FollowerListReq) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *FollowerListReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FollowerListReq(%+v)", *p)
}

type FollowerListResp struct {
	Base  *base.BaseResp     `thrift:"Base,1" form:"Base" json:"Base" query:"Base"`
	Items []*SocialItemsResp `thrift:"Items,2,default,list<SocialItemsResp>" form:"Items" json:"Items" query:"Items"`
	Total int32              `thrift:"total,3" form:"total" json:"total" query:"total"`
}

func NewFollowerListResp() *FollowerListResp {
	return &FollowerListResp{}
}

func (p *FollowerListResp) InitDefault() {
}

var FollowerListResp_Base_DEFAULT *base.BaseResp

func (p *FollowerListResp) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return FollowerListResp_Base_DEFAULT
	}
	return p.Base
}

func (p *FollowerListResp) GetItems() (v []*SocialItemsResp) {
	return p.Items
}

func (p *FollowerListResp) GetTotal() (v int32) {
	return p.Total
}

func (p *FollowerListResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *FollowerListResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FollowerListResp(%+v)", *p)
}

type FriendsListReq struct {
	PageNum      int32  `thrift:"page_num,1" json:"page_num" query:"page_num"`
	PageSize     int32  `thrift:"page_size,2" json:"page_size" query:"page_size"`
	AccessToken  string `thrift:"access_token,3" header:"Access-Token" json:"access_token"`
	RefreshToken string `thrift:"refresh_token,4" header:"Refresh-Token" json:"refresh_token"`
}

func NewFriendsListReq() *FriendsListReq {
	return &FriendsListReq{}
}

func (p *FriendsListReq) InitDefault() {
}

func (p *FriendsListReq) GetPageNum() (v int32) {
	return p.PageNum
}

func (p *FriendsListReq) GetPageSize() (v int32) {
	return p.PageSize
}

func (p *FriendsListReq) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *FriendsListReq) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *FriendsListReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FriendsListReq(%+v)", *p)
}

type FriendsListResp struct {
	Base  *base.BaseResp     `thrift:"Base,1" form:"Base" json:"Base" query:"Base"`
	Items []*SocialItemsResp `thrift:"Items,2,default,list<SocialItemsResp>" form:"Items" json:"Items" query:"Items"`
	Total int32              `thrift:"total,3" form:"total" json:"total" query:"total"`
}

func NewFriendsListResp() *FriendsListResp {
	return &FriendsListResp{}
}

func (p *FriendsListResp) InitDefault() {
}

var FriendsListResp_Base_DEFAULT *base.BaseResp

func (p *FriendsListResp) GetBase() (v *base.BaseResp) {
	if !p.IsSetBase() {
		return FriendsListResp_Base_DEFAULT
	}
	return p.Base
}

func (p *FriendsListResp) GetItems() (v []*SocialItemsResp) {
	return p.Items
}

func (p *FriendsListResp) GetTotal() (v int32) {
	return p.Total
}

func (p *FriendsListResp) IsSetBase() bool {
	return p.Base != nil
}

func (p *FriendsListResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FriendsListResp(%+v)", *p)
}

type SocialService interface {
	RelationAction(ctx context.Context, req *RelationActionReq) (r *RelationActionResp, err error)

	FollowingList(ctx context.Context, req *FollowingListReq) (r *FollowingListResp, err error)

	FollowerList(ctx context.Context, req *FollowerListReq) (r *FollowerListResp, err error)

	FriendsList(ctx context.Context, req *FriendsListReq) (r *FriendsListResp, err error)
}
