// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	interaction "video_website/biz/router/interaction"
	social "video_website/biz/router/social"
	user "video_website/biz/router/user"
	video "video_website/biz/router/video"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	video.Register(r)

	user.Register(r)

	social.Register(r)

	interaction.Register(r)

}
