// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package base

import (
	"fmt"
)

type BaseResp struct {
	Code int32  `thrift:"Code,1" form:"Code" json:"Code" query:"Code"`
	Msg  string `thrift:"Msg,2" form:"Msg" json:"Msg" query:"Msg"`
}

func NewBaseResp() *BaseResp {
	return &BaseResp{}
}

func (p *BaseResp) InitDefault() {
}

func (p *BaseResp) GetCode() (v int32) {
	return p.Code
}

func (p *BaseResp) GetMsg() (v string) {
	return p.Msg
}

func (p *BaseResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseResp(%+v)", *p)
}
